global.EnemyData = {
	"1" : { //Test 1
		MyName : "Test_Fighter_1",
		MyMaxHp : 100,
		MyAtk : 5,
		MyDef : 5,
		ShowBar : true,
		CanSpare : false,
		CanFlee : false,
		StartX : 300,
		StartY : 100,
		ObjRef : obj_fighter_test,
		EXP : 10,
		GOLD : 20,
	},
	"2" : { //Test 2
		MyName : "Test_Fighter_2",
		MyMaxHp : 100,
		MyAtk : 5,
		MyDef : 5,
		ShowBar : true,
		CanSpare : false,
		CanFlee : false,
		StartX : 300,
		StartY : 300,
		ObjRef : obj_fighter_test_1,
		EXP : 10,
		GOLD : 20,
	},
	"999" : { //Devo Trailer
		MyName : "[REDACTED]",
		MyMaxHp : 100,
		MyAtk : 5,
		MyDef : 9999999,
		ShowBar : true,
		CanSpare : false,
		CanFlee : false,
		StartX : 320,
		StartY : 75,
		ObjRef : obj_trailer_devo,
		EXP : 10,
		GOLD : 20,
	},	
}